name: Latest github activity
on:
  schedule:
    # cron: minute | hour | day of month | month | day of week
    # hier: alle viertel Stunde
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_LOG_TOKEN }}
        with:
          COMMIT_MSG: 'Updated Git-Hub-Activities'
          MAX_LINES: 6
